language: php

git:
  depth: 1

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache

php:
- 7.1
- 7.2

install:
- composer install

script:
- composer grumphp

after_success:
- phpenv config-rm xdebug.ini
- composer scrutinizer
- composer apigen

env:
  global:
  - secure: PgbKOQvF6wDx74EOBkH8aJ2ctkZPXZU/g0lHoPqXuW5rAZDcGYuy1Hb6oRKTGh1DiZ3onUxSQ44Y6H6C0o0hGLUepta/BhyTbTw8f4bYfyMTO/1rvmn0hZ8/y2dQz3XmfeXRBz2vyjfKZkEiSOSd73+d0csEPUTSScKQmSPEZ9H9oooRZtegwlrKdWPkZ/Gy+mxhX1nxLYvdWHAE0KFo0FWWy8OrUv0A0ndtbEeI99e+QNHF0NbmFxgi1VdJ3kznbfjIDJTqlhbyaN2gS+d3TJf3WzZQdLcURN4K7FIUAvNicwD0SmMxf5eUYujGP901B/NNIocaLVjzFLfUXIlhJYjQMd36Nc+uvQjdEUxtTzxWoZi3gLSL6WTPI6zoAzl/XWhIK421DwaV4tlPTpIyfQyozCdkZWJp05WiUh7dbBlDgZC8TzKoO/lIftRK5AGPtjyOegPtqa1SUlRNg7FhJQhMzkum7w40+AjQh/LEC/GtGQ0zq2UtDC+dCOjKmw28aia4m951eWEXIHJyjbvaUlIiEqc5AMr2P9gklcM0F86DV5IGTYSurqPfIsInMdn76PW55Cxj0LtDeLsvlGb5WQpmnheIAK2tGBA9qEC06QnCSe/cgxV86TsdLenwaerEdoL5Zzgc+KhXN8Bx/nCt9XUzQld/HnkYG1mJuH7kLhU=
  - secure: fPbL02gE1fX1CWK++Ck8711soBwo2EMZGVmm6nbp/y/sZFcZl3Ug8hrB0ov0cUHc9Z2yxGxv22EXdVE/1hylz5xDUnAMvNAtpjr6cZoto4ccZ6QkRZLEt31JK4/WQZNHK+msUaanavyCI1FQgjNe0h7LSpeGoGG4GOhtneO17Rropkbl+RJXyZUS4c0Ppf4mgWwUlbPat2qzSBFYU60ICJNY+/tCwOU6joPkoW+5EfRt1K6ZBOVB+eUKVS7xBZ8zvj/mq7rheMwF/NgfpFNSlr5oOhCF16TG2L9gGIgI0SJnPawdSnVnFOExvqBRgEeNlPIuKi1xOyoPpfxcHLf1l+LQS5bG8avFWxt9iEuls06lBqMtrr2u2r0+F8fRPQEzaJX3mtQi5uOediyRs9g3GwLcq/S72/ifOEIWddj8Vg7CM5gWe2lu4nt9YIIOr4ujgooRqnyAOQY5tm+72ElfAPOo0GXUV85GoPUWlVJ1GiDF4wtLU1mn9i3tNwhJTeNbeneOFA2VaCWtQN78Xc/XFyocD/R2fuycYYsnQUx1T10O0QTe/cGSfS8rT9JpIcn6tdi/Un+SKYcZv0e5MVa0PJ2SMWROeqcRxfh6sbTT6l+8eiyd4IrvgEH8Fxxe3wYOswyanUm4SD4JcOehCIgGRmIVMzNnVbbvFZOb8N0wauM=

deploy:
  local-dir: build/docs
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master