# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  - pull_request
  - push

name: "Continuous Integration"

jobs:
  grumphp:
    name: "Grumphp"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-binary:
          - php7.1
          - php7.2
          - php7.3

    steps:
      - name: "Checkout"
        uses: actions/checkout@master
        with:
            fetch-depth: 1

      - name: "Composer install"
        run: ${{ matrix.php-binary }} $(which composer) install --no-interaction --no-progress --no-suggest

      - name: "Composer install lowest dependencies"
        if: matrix.dependencies == 'lowest'
        run: ${{ matrix.php-binary }} $(which composer) update --no-interaction --no-progress --no-suggest --prefer-lowest

      - name: "Run Grumphp"
        run: ${{ matrix.php-binary }} vendor/bin/grumphp run
        env:
            STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: "Scrutinizer"
        run: wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
